### ISSUE TITLE
libvis

### ISSUE THREAD

**Issue by samsartor** [ColoradoSchoolOfMines/visplay#14]
This issue contains discussion and progress updates on the creation of `libvis`. `libvis` will be a common library for both visplay clients and content servers. It has no opinions on actual asset/playlist data, and does not contain any playback logic. Its job is to understand the content graph  (all the linked-together `source.yml`s).  `libvis` is responsible for:
- Reading `*.yml` files
- Walking the content graph
- Watching/publishing version info
- Listening/broadcasting on websockets

Fundamentally, `libvis` understands sources, asset/playlist versioning/metadata, and the websocket protocol. `libvis` does not understand the actual format of individual asset and playlist specifications (i.e. `http://cdn.mines.edu/advert.mp4` or `[vid0, corgies_pic for 3s, acm_announcements for 15s]`). Notably, `libvis` does not actually download assets, it only downloads the `*.yml` files. Users can lookup the asset specification, and then download/stream/cache the asset themselves.

Proposed implementation ideas:
- _Within_ `libvis`, playlists and assets should simply be "specifications" with specification types of "playlist" and "asset" respectively. Since `libvis` does not care about the actual data, all specifications are simply dropped into a single, huge dictionary. Only users of `libvis` care about the type of each spec (asset/playlist).
- Use sqllite (through an ORM such as [Diesel](http://diesel.rs/)) to maintain a "universe map" (a flattened, persistent copy of all specifications and metadata). This map is used to lookup asset and playlist specs, diff against new versions of `*.yml`s, and maintain versioning information. The map would only be updated as specifications and sources out in the world are changed, or as changes come in through a websocket. When the user asks for the specification of a given asset or playlist, `libvis` simply queries the universe map. Also, restarting visplay would not require the entire content graph to be rewalked. This also allows content updates to be made asynchronously, without interrupting playback (a tricky problem already solved by databases, why should we reinvent the wheel?).
- `libvis` can send a variety events, informing users when something is added/removed/changed.
- Although `libvis` does not download assets itself, it might ask the user to provide a "checksum" function which knows how to download and summarize the actual data behind a specification. For a playlist, the checksum would simply be 0. For an asset, it might be an actual hash.

At the end of the day, the `libvis` API should be very simple. Not much more than:

`set_checksummer(function)`
`get_specification(type, id) -> Object`
`on_change(callback)`
`on_command(callback)`

**Comment by jhgarner** [comment]
Splitting out the common behavior sounds good. What would the data being sent from a server instance of libvis to the client look like?

**Comment by samsartor** [comment]
I am doing some Rust for this on the `libvis` branch.

**Comment by robozman** [comment]
Closing the as per our discussion during the hackaton. It was decided the websocket code was best left in python and we are implementing many of the other proposed changes in the main python codebase.
