### ISSUE TITLE
Generate Config Folder and Default Config On First Launch

### ISSUE THREAD

**Issue by robozman** [ColoradoSchoolOfMines/visplay#3]
Currently we're looking in $XDG_CONFIG_HOME, then $HOME/.config.
Maybe we want to alter the second option to be $HOME/.config/visplay and create the directory if it doesn't exist.
@jhgarner

**Comment by jhgarner** [comment]
That would probably be good so that the user's config folder can stay organized. Later on, would it make sense to create a default file and write it as well if nothing else is found?

**Comment by robozman** [comment]
Yeah, creating a default config makes sense. We would have to make the folder as well. 

Should we make just the visplay.yaml or some/all of the others? We could just pull them from github.

**Comment by robozman** [comment]
Removing myself as this would be a good task for someone new to the codebase

**Comment by sumnerevans** [comment]
Fixed by #17.
