### ISSUE TITLE
Break up visplay.yaml

### ISSUE THREAD

**Issue by robozman** [ColoradoSchoolOfMines/visplay#6]
I think it would be a good idea to break up visplay.yaml into visplay.yaml, for general configuration and sources.yaml for locations of assets/sources/playlists.yaml.

Thoughts?

**Comment by jhgarner** [comment]
That sounds good and should be extremely easy since it would just be a rename. Visplay.config doesn't have support for anything but sources.

**Comment by robozman** [comment]
Great! I think it will also make https://github.com/ColoradoSchoolOfMines/visplay/issues/5 easier as we will not have to worry about ignoring non source related settings when obtained recursivly.

**Comment by robozman** [comment]
Requirements
- [ ] update visplay to look at the correct files
- [ ] make *.yaml.example files 
- [ ] update configuration creation instructions in the README
- [ ] document configuration format

**Comment by robozman** [comment]
I'm breaking visplay,yaml into config.yaml and sources.yaml. Better naming imo

**Comment by robozman** [comment]
@jhgarner The README needs to be updated to your new config syntax

**Comment by robozman** [comment]
This seems to be finished. We have settled on main entrypoint config.yaml, and sources.yaml files that can point to assets/playlists.yaml and import other sources.
